spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://192.168.56.101:1433;DatabaseName=stutyAssistant
    username: sa
    password: sasa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
